### ISSUE TITLE
Failed to load - NC 28.0.5

### ISSUE THREAD

**Issue by pbuergi** [rcdevs/nextcloud_openotp_auth#15]
Since the last update of the App (OpenOTP) there is an error after username and password login:

![image](https://github.com/rcdevs/nextcloud_openotp_auth/assets/156188834/729167aa-ad50-4026-9770-2f95bd84ea46)

![image](https://github.com/rcdevs/nextcloud_openotp_auth/assets/156188834/0678f806-4640-4dc0-9dfa-0c2e029ea70d)

We didn't change any settings. On the default policy (only one) we have the default domain active.
App-Settings:
![image](https://github.com/rcdevs/nextcloud_openotp_auth/assets/156188834/81bb2f44-5754-47e3-8f3a-2b199f34c08d)

We still can login, but always have to click on the OTP Provider.

Can you help?

Thanks

**Comment by rcdevs** [comment]
Hello,

This is because multiple authentication providers are enabled for the user accounts. In the plugin configuration, when you select "enable OpenOTP for all users," it makes the OpenOTP provider available for all users. It does not enforce OpenOTP as the only provider available for users. If you don't want users to be prompted to choose their provider, you have to disable other providers for all accounts.

Regards

**Comment by pbuergi** [comment]
Hi,

But we don't have another provider active.

**Comment by rcdevs** [comment]
You have the "backup code" provider enabled. 

Regards

**Comment by pbuergi** [comment]
I don't know where, but also not the case by other user:
![image](https://github.com/rcdevs/nextcloud_openotp_auth/assets/156188834/4408b2bf-2ee6-41eb-84dc-12204a4d0921)

**Comment by pbuergi** [comment]
I solved it:

get providers for user: `occ twofactorauth:state  username`
`occ twofactorauth:cleanup providername`

now it works fine.

Thank you for your help
